-- Tags system (replaces categories as primary post tagging)
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS post_tags (
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

-- Rank system for users
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS rank TEXT DEFAULT 'new_member';

-- Function to update rank based on post count
CREATE OR REPLACE FUNCTION update_user_rank()
RETURNS TRIGGER AS $$
DECLARE
  post_count INT;
BEGIN
  SELECT COUNT(*) INTO post_count FROM posts WHERE user_id = NEW.user_id;

  UPDATE profiles SET rank =
    CASE
      WHEN post_count >= 500 THEN 'well_known_developer'
      WHEN post_count >= 200 THEN 'developer'
      WHEN post_count >= 50 THEN 'senior_member'
      WHEN post_count >= 10 THEN 'member'
      ELSE 'new_member'
    END
  WHERE id = NEW.user_id AND is_admin = FALSE;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_update_rank ON posts;
CREATE TRIGGER trigger_update_rank
  AFTER INSERT ON posts
  FOR EACH ROW
  EXECUTE FUNCTION update_user_rank();

-- Set admin rank for admin user
UPDATE profiles SET rank = 'admin' WHERE is_admin = TRUE;

-- Function to ensure admin always has admin rank
CREATE OR REPLACE FUNCTION ensure_admin_rank()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_admin THEN
    NEW.rank := 'admin';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_ensure_admin_rank ON profiles;
CREATE TRIGGER trigger_ensure_admin_rank
  BEFORE INSERT OR UPDATE OF is_admin ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION ensure_admin_rank();
